### ISSUE TITLE
Views failing if document indexed more than once in a design

### ISSUE THREAD

**Issue by paulharter** [couchbase/sync_gateway#1556]
Hi

I've been getting strange behaviour with views created through the sync gateway sometimes failing. I had thought that it was due to a bug in Couchbase Server but it looks like it's an issue with Sync Gateway's indexing.

Also I get it if I run using sync gateway 1.1.1 under ubuntu 14.04 in a docker but not if I run a recent build locally on osx.

It looks like if two views in a design document both index the same document then only one of them will index it correctly. Also which one of the two view succeeds seems to be deterministically affected by minor white space changes the the javascript. It is as if the views in a design were being sorted by a hash of their javascript and then on indexing only the first to succeed indexes a document. 

I'm guessing this is a bug and not expected behaviour

I have put a failing test that shows this in a gist

https://gist.github.com/paulharter/1aa4f32269f8c38fe9c5

P

**Comment by paulharter** [comment]
I have just run the test with the most recent docker images for couchbase and sync gateway and it is failing to index correctly. Could this be os dependent?

``` yaml
couchbase:
  container_name: couchbase
  image: couchbase:4.1.0
  net: host

sync_gateway:
  container_name: sync_gateway
  image: couchbase/sync-gateway:1.2.0-rc1
  net: host
  restart: always
  ports:
    - "4985:4985"
    - "4984:4984"
  ...
```
